{% set name = "txm_sandbox" %}
{% set version = "0.3.1.post6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e6020ab72292ddb2ec85c7150561a95bce22526dc3be859e7b685ec65d1b49b 

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.11
    - pip
  run:
    - python >=3.11
    - openjdk =8
    - pyimagej
    - nodejs
    - xarray
    - tomopy
    - h5py
    - tifffile
    - opencv
    - openpyxl
    - pytables
    - pandas
    - jupyter
    - jupyterlab
    - multiprocess
    - scikit-image
    - scikit-learn
    - pystackreg
    - silx
    - napari

test:
  imports:
    - txm_sandbox

about:
  home: https://github.com/xianghuix/TXM_Sandbox
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Integrated Spectro-Imaging Analysis Toolbox

  description: |
    TXM_Sandbox is a GUI program based on Jupyter that integrates
    tomography reconstruction and 2D/3D XANES data analysis. It 
    provides a mechanism for users to accomendate different input
    file formats.

  dev_url: https://github.com/xianghuix/TXM_Sandbox

extra:
  recipe-maintainers:
    - xianghuix
